site_name: Hive
site_description: python wrapper for the XAUTOMATA API
site_url: https://www.xautomata.com/

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - navigation.sections
    - navigation.top
    - navigation.expand
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.follow
    - header.autohide

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: orange
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: orange
      accent: lime

repo_name: xautomata-hive
repo_url: https://github.com/sherlogic/xautomata-hive.git

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - XA information: info.md
  - API:
      - hive:
        - api: hive.api
        - decorators: hive.decorators
        - exceptions: hive.exceptions
        - infrastrucure_keys: hive.infrastrucure_keys
        - version: hive.version
        - cookbook:
          - acl_docs: hive.cookbook.acl_docs
          - acl_overrides: hive.cookbook.acl_overrides
          - analytics: hive.cookbook.analytics
          - anomalies: hive.cookbook.anomalies
          - calendars: hive.cookbook.calendars
          - contacts: hive.cookbook.contacts
          - cost_tagging: hive.cookbook.cost_tagging
          - cost_tags: hive.cookbook.cost_tags
          - cost_views: hive.cookbook.cost_views
          - customers: hive.cookbook.customers
          - dashboards: hive.cookbook.dashboards
          - dispatchers: hive.cookbook.dispatchers
          - downtimes: hive.cookbook.downtimes
          - external_tickets: hive.cookbook.external_tickets
          - features: hive.cookbook.features
          - firmware_updates: hive.cookbook.firmware_updates
          - google: hive.cookbook.google
          - groups: hive.cookbook.groups
          - jobs: hive.cookbook.jobs
          - last_status: hive.cookbook.last_status
          - login: hive.cookbook.login
          - messages: hive.cookbook.messages
          - metrics: hive.cookbook.metrics
          - metric_ingest: hive.cookbook.metric_ingest
          - metric_types: hive.cookbook.metric_types
          - microsoft: hive.cookbook.microsoft
          - notification_providers: hive.cookbook.notification_providers
          - notification_provider_types: hive.cookbook.notification_provider_types
          - objects: hive.cookbook.objects
          - opening_reasons: hive.cookbook.opening_reasons
          - probes: hive.cookbook.probes
          - probes_log_ingest: hive.cookbook.probes_log_ingest
          - probe_types: hive.cookbook.probe_types
          - profile_topics: hive.cookbook.profile_topics
          - reason_for_closure: hive.cookbook.reason_for_closure
          - retention_rules: hive.cookbook.retention_rules
          - schedules: hive.cookbook.schedules
          - services: hive.cookbook.services
          - sites: hive.cookbook.sites
          - terms_and_conditions: hive.cookbook.terms_and_conditions
          - tree_hierarchy: hive.cookbook.tree_hierarchy
          - ts_cost_azure_raw: hive.cookbook.ts_cost_azure_raw
          - ts_cost_management: hive.cookbook.ts_cost_management
          - ts_metric_status: hive.cookbook.ts_metric_status
          - ts_metric_value: hive.cookbook.ts_metric_value
          - ts_ntop_flows: hive.cookbook.ts_ntop_flows
          - ts_service_status: hive.cookbook.ts_service_status
          - ts_service_value: hive.cookbook.ts_service_value
          - users: hive.cookbook.users
          - users_notifications: hive.cookbook.users_notifications
          - virtual_domains: hive.cookbook.virtual_domains
          - webhooks: hive.cookbook.webhooks
          - widgets: hive.cookbook.widgets
          - widget_groups: hive.cookbook.widget_groups

copyright:
  MIT
