name: Trigger Build Hive al Rilascio Tag API

on:
  repository_dispatch:
    types: [new-tag]

jobs:
  new-api-tag-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get TAG
        run: |
          echo ${{ github.event.client_payload.tag}}
          echo cat "version = '${{ github.event.client_payload.tag}}'" > version.py 

# crea documentazione
  documentation:
    runs-on: ubuntu-latest
    needs: new-api-tag-generated
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install "mkdocstrings[python]"
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force

# deply su PyPi
  pypi_deploy:
    runs-on: ubuntu-latest
    needs: documentation
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.2
      with:
          github_repo: sherlogic/xautomata-hive
          twine_username: ${{ secrets.PYPI_NAME }}
          twine_password: ${{ secrets.PYPI_PASS }}
          verify_metadata: true
          skip_existing: true
          verbose: true
    

        
    
