name: Trigger Build Hive al Rilascio Tag API

on:
  repository_dispatch:
    types: [new-tag]

jobs:
  get-TAG:
    runs-on: ubuntu-latest
    steps:
      - name: get-tag
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}

    

        
    
