name: Trigger Build Hive al Rilascio Tag API

on:
  repository_dispatch:
    types: [new-tag]


permissions:
  contents: write


jobs:
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so tags are available

      # otteniamo il payload inviato da API ENV
      - name: get new TAG
        id: get_payload
        run: |
          echo "PAYLOAD=${{github.event.client_payload.tag}}" >> $GITHUB_OUTPUT
          echo "Payload received."
          echo "TAG: $PAYLOAD"

      #otteniamo ultimo tag nella repo
      - name: Get current tag
        id: get_current_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT


      #leggiamo la versione scritta sul file
      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat hive/version.py | grep -oP "(?<=version = ')[^']*")" >> $GITHUB_OUTPUT
    

      #confrontiamo la version scritta sul file col payload
      #se il payload ha un valore diverso dal tag attuale allora va bene usarlo come confronto
      #se il payload ha lo stesso valore del tag, allora usare PAYLOAD o CURRENT_TAG non cambia
      - name: Check if version has changed
        id: version_changed 
        run: |
          PAYLOAD="${{ steps.get_payload.outputs.PAYLOAD }}"
          CURRENT_TAG="${{ steps.get_current_tag.outputs.TAG }}"
          CURRENT_VERSION="${{ steps.get_version.outputs.VERSION }}"

          if [ "$PAYLOAD" != "$CURRENT_TAG" ]; then
            echo "TAG has changed. New tag is $PAYLOAD"
            echo "TAG_CHANGED=true" >> $GITHUB_OUTPUT
            CURRENT_TAG="${{ steps.get_payload.outputs.PAYLOAD }}"
          else
            echo "TAG has not changed."
            echo "TAG_CHANGED=false" >> $GITHUB_OUTPUT
          fi

          
          if [ "$CURRENT_TAG" != "$CURRENT_VERSION" ]; then
            echo "Version has changed. New version is $PAYLOAD"
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "Version has not changed."
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi
  

  #se il tag è diverso creiamo il nuovo tag dandogli il valore ricevuto
      - name: Create new tag
        id: create_new_tag
        if: ${{ steps.version_changed.outputs.TAG_CHANGED == 'true' }}
        run: |
            TAG_NAME=${{ github.event.client_payload.tag }}
            git tag $TAG_NAME
            git push origin $TAG_NAME

      - name: Update txt file version
        run: |
          TAG_NAME=${{ github.event.client_payload.tag }}
          echo "tag version: '$TAG_NAME'"
          ls -l version.txt
          echo "version = 'C.B.A'" > version.txt
          cat version.txt
          git add version.txt

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git commit -m "Update version.txt"
          git push
          
  #scriviamo la nuova versione nel file
      - name: Update file version
        id: update_file_version
        if: ${{ steps.version_changed.outputs.VERSION_CHANGED == 'true' }}
        run: |
          TAG_NAME=${{ github.event.client_payload.tag }}
          echo "tag version: '$TAG_NAME'"
          ls -l hive/version.py
          echo "version = '$TAG_NAME'" > hive/version.py
          cat hive/version.py

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add hive/version.py
          git commit -m "Update hive/version.py"
          git push


# questa azione si attiva solo se quella subito prima ha creato un nuovo tag con successo
  documentation:
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install "mkdocstrings[python]"
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force

# This action will be triggered when you have created the documentation
  pypi_deploy:
    runs-on: ubuntu-latest
    needs: documentation
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.2
      with:
          github_repo: sherlogic/xautomata-hive
          twine_username: ${{ secrets.PYPI_NAME }}
          twine_password: ${{ secrets.PYPI_PASS }}
          verify_metadata: true
          skip_existing: true
          verbose: true

